theme = "wolf-alabaster-light"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
default-yank-register = "+"
end-of-line-diagnostics = "hint"
insert-final-newline = true
rulers = [120]
scrolloff = 1
shell = ["bash", "-c"]
trim-final-newlines = true
trim-trailing-whitespace = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "none"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal.backspace]
f = ":reflow 120"
d = ":set-option inline-diagnostics.cursor-line disable"
D = ":set-option inline-diagnostics.cursor-line warning"
a = ":set line-number absolute"
r = ":set line-number relative"
w = ":set whitespace.render none"
W = ":set whitespace.render all"
